{% set name = "python-lsp-server" %}
{% set version = "1.7.1" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67473bb301f35434b5fa8b21fc5ed5fac27dc8a8446ccec8bae456af52a0aef6

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

outputs:
  - name: {{ name|lower }}-base
    version: {{ version }}
    build:
     number: {{ build_number }}
     noarch: python
     script: python -m pip install . --no-deps --no-build-isolation -vv
     entry_points:
       - pylsp = pylsp.__main__:main
    requirements:
      host:
        - python >=3.7
        - pip
        # Needed at build time to produce a package with the correct version for pip
        # See https://github.com/pypa/setuptools_scm/issues/636#issuecomment-1026435048
        - setuptools_scm >=3.4.3
      run:
        - python >=3.7
        - jedi >=0.17.2,<0.19
        - python-lsp-jsonrpc >=1.0.0
        - pluggy >=1.0.0
        - docstring-to-markdown
        - ujson >=3.0
        - setuptools >=39.0.0
    test:
      requires:
        - pip
      commands:
        - python -m pip check
        - pylsp --help
        # The pip version can be reported incorrectly if setuptools_scm isn't available
        # at build time.
        # Based on https://github.com/conda-forge/pyusb-feedstock/pull/4
        - pip list | grep -i python-lsp-server | grep {{ version }}

  - name: {{ name|lower }}
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage("python-lsp-server-base", exact=True) }}
        - autopep8 >=1.6.0,<1.7.0
        - flake8 >=5.0.0,<7.0.0
        - mccabe >=0.7.0,<0.8.0
        - pycodestyle >=2.9.0,<2.11.0
        - pydocstyle >=6.2.0,<6.3.0
        - pyflakes >=2.5.0,<3.1.0
        - pylint >=2.5.0,<3.0.0
        - rope >=1.2.0
        - whatthepatch >=1.0.2,<2.0.0
        - yapf
    test:
      requires:
        - pip
      commands:
        - python -m pip check
        - pylsp --help
        # The pip version can be reported incorrectly if setuptools_scm isn't available
        # at build time.
        # Based on https://github.com/conda-forge/pyusb-feedstock/pull/4
        - pip list | grep -i python-lsp-server | grep {{ version }}

about:
  home: https://github.com/python-lsp/python-lsp-server
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of the Language Server Protocol for Python
  description: |
    A Python 3.7+ implementation of the Language Server Protocol
    making use of Jedi, pycodestyle, Pyflakes and YAPF.
  dev_url: https://github.com/python-lsp/python-lsp-server

extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
    - steff456
